### PR TITLE
Use web-animations.min.js

### PR DESCRIPTION
**Pull request by ewilligers**
Update most examples to use web-animations.min.js instead of
polyfill-loader.js (which loads web-animations-next.min.js).

### CODE REVIEW

**Comment by samthor** [comment]
LGTM

**Comment by alancutter** [comment]
Let's change polyfill-loader to use web-animations.min.js and the rest to use web-animations-next.min.js directly.

**Comment by samthor** [comment]
The only thing the loader does is look for 'nopolyfill' (which isn't in any sample right now), and does not include the code in that case. So I'd suggest removing it.

**Comment by alancutter** [comment]
That seems like a useful feature for testing, I'm inclined to keep it.

**Comment by alancutter** [comment]
Explicit references are nicer for debugging.

**Pull request merged**
